### ISSUE TITLE
docker run fails

### ISSUE THREAD

**Issue by nigelwhite** [civicrm/civicrm-docker#6]
I did
docker pull civicrm/civicrm
docker run -p 8000:80 civicrm/civicrm

Progress
[Tue Dec 10 09:22:43.318800 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.3.14 configured -- resuming normal operations
[Tue Dec 10 09:22:43.318822 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

Then
[Tue Dec 10 09:29:16.564940 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00169: caught SIGTERM, shutting down
and another time
[Tue Dec 10 09:30:55.440732 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00170: caught SIGWINCH, shutting down gracefully

Docker log
level=info msg="ignoring event" container=c4037df4b1921679f4b4b2f9d7eb0433eed85bef8d51b0b3b8fdeb5b778a429d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

Docker CE 27.4.0
Linux Mint 21.2

**Comment by michaelmcandrew** [comment]
hi @nigelwhite,

Nothing obvious leaps out at me.

From your logs, it looks like it is working for a few minutes and then shuts down. Were you doing anything specific at the time to cause that to happen?

Are you doing anything else special or just trying to run the image as you have described above?

**Comment by michaelmcandrew** [comment]
oh, actually, I do know what this is :)

when you run apache in a terminal, certain operations (like resizing the terminal) will cause it to issue a SIGWINCH which causes apache to exit. It is a bug in apache: https://bz.apache.org/bugzilla/show_bug.cgi?id=50669.

If you run it in the background by adding `-d` or `--detach` this will not happen.

**Comment by michaelmcandrew** [comment]
@nigelwhite - please close if this solves your problem.

**Comment by nigelwhite** [comment]
Thanks Michael

--detach made no difference. It gets as far as
[Wed Dec 11 08:40:41.341555 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.3.14 configured -- resuming normal operations
[Wed Dec 11 08:40:41.341577 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
then hangs

Maybe the SIGWINCH is a red herring - caused by me doing ^C to step out of the hang state?

I'm going to do some debugging / updating in my docker setup so leave it with me. I'll report back if I find anything.

**Comment by nigelwhite** [comment]
Ah, you were right! Thank you [I was putting the --detach in the wrong place]

**Comment by michaelmcandrew** [comment]
Glad it is sorted - can we close this issue now?
